server.port: 9999

spring:
  rabbitmq:
    port: 5672
    username: admin

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
