CREATE TABLE IF NOT EXISTS `board` (
    `id` MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(500) NOT NULL,
    `content` VARCHAR(2000) NOT NULL,
    `writer_id` MEDIUMINT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NULL
);